version: "3"
services:
  position:
    build:
      context: .
      dockerfile: ./position/Dockerfile
    environment:
      QRYPTOS_API_TOKEN_ID:
      QRYPTOS_API_SECRET_KEY:
      POSITION_BASE_CURRENCY: ETH
      POSITION_QUOTE_CURRENCY: BTC
      AWS_ACCESS_KEY_ID:
      AWS_SECRET_ACCESS_KEY:
  monitor:
    build:
      context: .
      dockerfile: ./monitor/Dockerfile
    environment:
      AWS_ACCESS_KEY_ID:
      AWS_SECRET_ACCESS_KEY:

