version: "3"
services:
  position:
    build:
      context: .
      dockerfile: ./position/Dockerfile
    environment:
      QRYPTOS_API_TOKEN_ID:
      QRYPTOS_API_SECRET_KEY:
      POSITION_BASE_CURRENCY: ETH
      POSITION_QUOTE_CURRENCY: BTC
